"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


def test_audit_all_clean():
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    audit_all_for_package(
        "scitex-hpc",
        skip_rules=(
            # README rewrite — needs ## Demo + ## Architecture sections
            # added per the canonical template. Tracked alongside the
            # next docs refresh.
            "PS-141",
            "PS-142",
            # `[dev]` extra missing scitex_dev — fixing requires deciding
            # whether to add it to [dev] or guard test imports with
            # importorskip; bundling with the next dependency-pin pass.
            "PS-210",
            # 3/5 Python APIs unmapped to MCP tools (sbatch/srun/sync) —
            # architectural parity gap, per-API decision needed.
            "§6",
        ),
    )
